services:
  app:
    container_name: user-management-app
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - XDEBUG_PORT=9000
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin
      - redis
    networks:
      - lion
  
  mailhog:
    image: mailhog/mailhog
    container_name: user-management-mailhog
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - lion
  
  redis:
    image: redis
    container_name: user-management-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: lion
      REDIS_DATABASES: 1
    networks:
      - lion
  
  mysql:
    image: mysql
    container_name: user-management-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lion_database
      MYSQL_PASSWORD: lion
      MYSQL_ROOT_PASSWORD: lion
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lion
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: user-management-phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: lion
      MYSQL_ROOT_PASSWORD: lion
    networks:
      - lion

volumes:
  mysql_data:
  redis_data:
    driver: local

networks:
  lion:
    driver: bridge